language: python
python:
  - "3.6"

before_install:
  - >-
    openssl aes-256-cbc 
    -K $encrypted_9a69ea8ca554_key 
    -iv $encrypted_9a69ea8ca554_iv 
    -in travis_deploy.enc 
    -out travis_deploy 
    -d

  - sudo apt-get -qq update
  - wget https://github.com/jgm/pandoc/releases/download/2.9.1.1/pandoc-2.9.1.1-1-amd64.deb
  - sudo dpkg -i ./pandoc-2.9.1.1-1-amd64.deb

install:
  - sudo apt-get install -y nodejs npm
  - pip install pipenv
  - pipenv install

script:
  - make
  - cp README.md html/

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  verbose: true
  local_dir: build
  on:
    branch: master
